### ISSUE TITLE
Documentation ins unclear of "parent" argument when creating a repository

### ISSUE THREAD

**Issue by g-emarco** [googleapis/python-artifact-registry#207]
#### Environment details

- This issue is regarding documentation 
#### Steps to reproduce

Go to the generated doc page:
https://cloud.google.com/python/docs/reference/artifactregistry/latest/google.cloud.artifactregistry_v1.services.artifact_registry.ArtifactRegistryClient#google_cloud_artifactregistry_v1_services_artifact_registry_ArtifactRegistryClient_create_repository

#### Description:
In the **CreateRepositoryRequest** documentation it says in the function documetnation that:

`    r"""The request to create a new repository.

    Attributes:
        parent (str):
            Required. The name of the parent resource
            where the repository will be created.
        repository_id (str):
            The repository id to use for this repository.
        repository (google.cloud.artifactregistry_v1beta2.types.Repository):
            The repository to be created.
    """`

However it is unclear what is the "resource" for the argument **parent**, it is not clear what to put in this argument.
Also, in the docs link,  the example shown doesn't imply or hint what should sent in this argument. 

Thanks!

**Comment by parthea** [comment]
Hi @g-emarco,

I'm sorry for the delay in responding.

The `parent` should be populated as follows.

```
parent="projects/<PROJECT_ID>/locations/<LOCATION>"
```

For reference, see https://cloud.google.com/artifact-registry/docs/reference/rest/v1/projects.locations.repositories/create for the REST API which shows the format as `parent=projects/*/locations/*`

I'm going to close this issue but please feel free to open a new issue if you're still having trouble.
